const cssProperties: string[] = [
    'box-sizing:border-box;',
    'font-family:sans-serif;',
    'line-height:1.15;',
    '-webkit-text-size-adjust:100%;',
    '-webkit-tap-highlight-color:rgba(0, 0, 0, 0);',
    'display:block;',
    'margin:0;',
    'font-family:-apple-system, BlinkMacSystemFont, "SegoeUI", Roboto, "HelveticaNeue", Arial, "NotoSans", sans-serif, "AppleColorEmoji", "SegoeUIEmoji", "SegoeUISymbol", "NotoColorEmoji";',
    'font-size:1rem;',
    'font-weight:400;',
    'line-height:1.5;',
    'color:#212529;',
    'text-align:left;',
    'background-color:#fff;',
    'outline:0!important;',
    'box-sizing:content-box;',
    'height:0;',
    'overflow:visible;',
    'margin-top:0;',
    'margin-bottom:0.5rem;',
    'margin-top:0;',
    'margin-bottom:1rem;',
    'text-decoration:underline;',
    '-webkit-text-decoration:underlinedotted;',
    'text-decoration:underlinedotted;',
    'cursor:help;',
    'border-bottom:0;',
    '-webkit-text-decoration-skip-ink:none;',
    'text-decoration-skip-ink:none;',
    'margin-bottom:1rem;',
    'font-style:normal;',
    'line-height:inherit;',
    'margin-top:0;',
    'margin-bottom:1rem;',
    'margin-bottom:0;',
    'font-weight:700;',
    'margin-bottom:.5rem;',
    'margin-left:0;',
    'margin-left:0',
    '     margin:001rem;',
    '$warning_background_color : $white !default;',
];


export default cssProperties;